name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          python-version: 3.8
      # Install an ipykernel so it is available for tests
      - run: |
          python3 -m pip install --upgrade pip
          pip3 install setuptools ipykernel --upgrade
          python3 -m ipykernel install --user
      - run: npm ci
      - run: npm test
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
